<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="http://localhost/MoviesTask/movie/addMovie" method="post">
        <input type="text" name="title" id="">Title<br />
        <input type="text" name="year" id="">Year<br />
        <input type="text" name="format" id="">Format<br />
        <input type="text" name="actors" id="">Actors<br />
        <input type="submit" value="Add movie">
    </form>
</body>
</html>