<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="http://localhost/MoviesTask/search/search" method="post">
    
        <input type="text" name="value" id="">
        <input type="radio" name="type" id="" value = "actor">Actor
        <input type="radio" name="type" id="movie" value = "movie">Movie
        <input type="submit" value="sub">
    
    </form>
</body>
</html>